### ISSUE TITLE
Can we match different cloak_patterns to different types of files?

### ISSUE THREAD

**Issue by pypeaday** [laytan/cloak.nvim#1]
Basically title... It'd be awesome to match different patterns in different files. 

I have 2 main types of secret files. 1 is yaml that has things like `con: my-secret-connection-info` and the other is like your example, .env files with `MYSECRET=...`. I'd like to match both but am struggling to get it right - can you toss an example in the README or is this not possible at the moment? 

PS - already love the plugin.. dox'd myself so many times on Teams calls...

**Comment by laytan** [comment]
Hey, this should be possible already.

Something like the following config should work for what you describe:

```lua
require('cloak').setup({
  patterns = {
    {
      -- Match any file ending in '.yml'. you can make this more specific, like 'secrets.yml', or even pass a list.
      file_pattern = '*.yml',
      -- Match a ':' and any character after it will be cloaked.
      cloak_pattern = ':.+'
    },
  },
})
```

If you also want to cloak lists in yml, you can do something like this:
```lua
require('cloak').setup({
  patterns = {
    {
      -- Match any file ending in '.yml'. you can make this more specific, like 'secrets.yml', or even pass a list.
      file_pattern = '*.yml',
      -- Match a ':' and any character after it will be cloaked.
      cloak_pattern = ':.+'
    },
    {
      -- Match any file ending in '.yml'. you can make this more specific, like 'secrets.yml', or even pass a list.
      file_pattern = '*.yml',
      -- Match a '-' and any character after it will be cloaked.
      cloak_pattern = '-.+'
    },
  },
})
```
Does this help?

**Comment by laytan** [comment]
I have added support for multiple cloaks per pattern, so the 2nd snippet can now be simplified using:
```lua
require('cloak').setup({
  patterns = {
    {
      file_pattern = '*.yml',
      cloak_pattern = {  ':.+', '-.+' },
    },
  },
})
```

I am also closing this because I assume everything is resolved.

**Comment by pypeaday** [comment]
Thanks! Sorry for the delay, lost this notification in my email. I will play around and come back if I have questions! Great plugin!
