### ISSUE TITLE
Error messages in Telescope since the new update (telescope preview feature)

### ISSUE THREAD

**Issue by bhargavaman** [laytan/cloak.nvim#15]
Here's a screenshot of the error message (this is displayed on every file preview)

<img width="1644" alt="image" src="https://github.com/laytan/cloak.nvim/assets/5390139/39b0ef56-5bf3-486a-bfad-254e6cd3b9bc">

The error does not popup when Cloak is disabled.

**Comment by AXVIII3** [comment]
Came to open the same issue

![image](https://github.com/laytan/cloak.nvim/assets/76608488/41b35ed3-3801-4fc1-a616-5f47e16ae644)

**Comment by jokesper** [comment]
This is due to #14 relying on features from telescope:master currently not in 0.1.x

**Comment by AXVIII3** [comment]
@jokesper cool thanks!

**Comment by laytan** [comment]
Sorry about this everyone, I should have tested it with the latest stable version of telescope too. I merged the fix @jokesper made a PR with.

**Comment by bhargavaman** [comment]
No worries mate, all good!
