### ISSUE TITLE
[Bug] cloak_telescope = true doesn't seem to work

### ISSUE THREAD

**Issue by Sergih28** [laytan/cloak.nvim#19]
Regardless if I add to the config `cloak_telescope = true`, `cloak_telescope = false` or don't add it at all, the password always shows in plain text in Telescope preview.
That same password does not show when viewing the file normally.

Am I  missing something? :thinking:

**Comment by Sergih28** [comment]
Wow! 2 minute difference and we created the same issue!
This is now a duplicate of #18

**Comment by laytan** [comment]
This was resolved in #18, you are probably not using a version of Telescope that supports the API we need.
