### ISSUE TITLE
Can we have cloak active in previews from other plugins such as telescope

### ISSUE THREAD

**Issue by Mithrandir2k18** [laytan/cloak.nvim#8]
The plugin works great but doesn't seem to apply itself to previews such as when showing a project search in e.g. telescope the preview should also be cloaked if applicable.

**Comment by laytan** [comment]
I looked into this when I first created the plugin but after a little bit I gave up, there wasn't a lot of documentation on changing Telescope this way and couldn't figure it out in due time. I fit is even possible that is.
I will put this on my list to try again and see if there are new APIs available on the Telescope side.

PRs are also welcome of course ;)

**Comment by jkeDev** [comment]
Hey,
I was working on a PR for this and it's mostly pretty simple.
Adding this autocmd* in setup does the job but only when you redraw the preview. E.g. after seeing the preview you have to see another and after switching back, it shows. I can't figure out why the extmarks are not showing
and I already confirmed that they are being executed and that what is showing
is the delayed result (i.e. when you append something it appends as predicted but not the first. prints and options still work on the first).
Maybe some of the `telescope.actions` could help but I am not sure.
I will (maybe) look at this at a later date again but I didn't want others starting from scratch.

*the autocmd:
```lua
vim.api.nvim_create_autocmd('User', {
    pattern = 'TelescopePreviewerLoaded',
    callback = function()
      if M.opts.enabled then
        M.cloak(pattern)
      end
    end,
    group = group,
  }
)
```

**Comment by martin-braun** [comment]
I'd also enjoy it to filter out suggestions from `coc.nvim` to be honest.

**Comment by laytan** [comment]
@martin-braun For that, when using nvim-cmp we detect and disable the plugin for the buffer. That is probably good to also add for coc.nvim.

**Comment by martin-braun** [comment]
@laytan Bit tricky, `coc.nvim` does more than code suggestions. Disabling it, disables more than just code suggestions, but thanks for the hint. There should be a way to disable code suggestions for `coc.nvim`. My primary concern is that it might still suggest a key while being in another buffer.

I mean, look at that:

<img width="815" alt="image" src="https://github.com/laytan/cloak.nvim/assets/24259245/df2648c4-41e4-4c9f-ae42-ea6550e3868d">

See how the `.inputrc` suggests a phrase from the `yml` below? I'm not sure if this logic comes from `coc.nvim`, but my Neovim seems to suggest things that are not symbols as well, especially when no LSP is present, which would be the case in .env files. 

Sadly, even quotes aren't stopped by it:

<img width="815" alt="image" src="https://github.com/laytan/cloak.nvim/assets/24259245/1cba9498-949b-47e0-9fc6-c9644cb0662a">

Will definitely have a look to it later, I first need to understand where those are coming from. My config btw: https://github.com/martin-braun/CocChad (based on NvChad)

**Comment by eslam-allam** [comment]
To add on @jokesper idea, here's my ugly solution to the telescope preview refresh problem.

Autocmd:

```lua
-- Telescope preview cloak
local cloak = require("cloak")
local action_state = require("telescope.actions.state")
vim.api.nvim_create_autocmd("User", {
  pattern = "TelescopePreviewerLoaded",
  callback = function(args)
    local buffer = require("telescope.state").get_existing_prompt_bufnrs()[1]
    local base_name = vim.fn.fnamemodify(args.data.bufname, ":t")
    local ok, _ = pcall(vim.api.nvim_buf_get_var, args.buf, "cloaked")
    for _, pattern in ipairs(cloak.opts.patterns) do
      for _, file_pattern in ipairs(pattern.file_pattern) do
        if vim.fn.match(base_name, file_pattern) >= 0 then
          cloak.cloak(cloak.opts.patterns[1])
          vim.api.nvim_buf_set_var(args.buf, "cloaked", true)
          if ok then
            return
          end
          action_state.get_current_picker(buffer):refresh()
          return
        end
      end
    end
  end,
  group = "cloak",
})
```

Here i`m addressing two things:

- Only cloak buffers that match file patterns defined in the cloak setup function.
- Refresh the Telescope picker after cloaking is applied.

If someone has a prettier way of doing this please let me know.
